# Introduction

Welcome to this notebook! 

This notebook provides a brief introduction to basic linear algebra targeting to execute various problem in quantum informaiton. 
In ths notebook, you will learn how to execute basic linear algebra using python, for example, matrix operation, eigenvalues, inner products. 

The questions about this material shall be addressed to Prof. Kazuki Ikeda kazuki.ikeda@umb.edu

# Install python packages for calculation

Install the required packages to get started. 
If you have not installed the follwoing pacages yet, you can do so by executing the following commands 

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


Now let's import packages

In [13]:
import numpy as np
from numpy import array, dot, pi
import scipy.sparse as sp
from scipy.sparse.linalg import eigsh
from scipy.linalg import eigvals

# Complex numbers

First, in python the complex unit $i$ is express by "1j". So for example, a complex number $5+2i$ is expressed as follows:

In [19]:
5+2j

(5+2j)

Multiplication is computed by applying "*" to complex numbers:

In [17]:
(5+2j)*(1-1j)

(7-3j)

The complex conjugate of a complex number $c$ can be computed by "np.conj(c)":

In [15]:
np.conj(5+2j)

(5-2j)

# Vectors

## Definition and operations

Here let's learn basic vector operations by python. 
First, define and plot a two-dimensional complex vector $v$. 
As an example, we use 
$$v=\begin{pmatrix}1+2i\\3-4i\end{pmatrix}$$

In [21]:
v= np.array([1 + 2j, 3 - 4j])
print(v)

[1.+2.j 3.-4.j]


Two complex vectors $v,u$ can be added. For example, when 
$$u=\begin{pmatrix}5+6i\\7-8i\end{pmatrix},$$
$u+v$ is 
$$v+u=\begin{pmatrix}6+8i\\10-12i\end{pmatrix},$$
which can be confirmed by python as follows

In [23]:
u= np.array([5 + 6j, 7 - 8j])
print(v+u)

[ 6. +8.j 10.-12.j]


## Complex conjugate

Complex conjugate of a vector $v$ is obtained by taking the complex conjugate of each component of $v$. Execute following command and compare the rsult with $v$. 

In [25]:
np.conj(v)

array([1.-2.j, 3.+4.j])

## Inner product and norm

The inner product of two complex vectors $v,u$ are defined by 
$$\langle v,u\rangle=\sum_{n=1}v^*_nu_n$$



With python, this can be computed by the following command: 

In [27]:
np.dot(np.conj(v).T,u)

(70+0j)

The norm of a vector is defined by $$\|v\|=\sqrt{\langle v,v\rangle}.$$
Note that this value is always real. Let's confirm this with python. 

In [29]:
np.sqrt(np.dot(np.conj(v).T,v))

(5.477225575051661+0j)

# Pauli operators 

The Pauli operators are the most fundamental operators in quantum information, and they are defined as follows:  
 $$X=\begin{pmatrix} 0&1\\ 1&0\end{pmatrix},~Y=\begin{pmatrix} 0&-i\\ i&0\end{pmatrix},~Z=\begin{pmatrix} 1&0\\ 0&-1\end{pmatrix}$$

Here we deine the Pauli operators using scipy, which is useful to calculate sparce matrices. 

In [33]:
def pauli_X():
    op=sp.csr_matrix([[0,1],[1,0]])
    return op

def pauli_Z():
    op=sp.csr_matrix([[1,0],[0,-1]])
    return op

def pauli_Y():
    op=sp.csr_matrix([[0,-1j],[1j,0]])
    return op

We can plot the matrix components of the Pauli X operator as follows 

In [35]:
print(pauli_X()) 

  (0, 1)	1
  (1, 0)	1


Here, only non-zero martrix components are shown. "(0,1) 1" means the (0,1) component of Pauli X is 1.  The components not shown are 0.  

# Matrix operations 

## Addition and Multiplication

Here we learn how to execute matrix operations. For matrices $A_1,A_2$, matrix addition and scalar multiplication are defined: 
$$c_1A_1+c_2A_2~(c_1,c_2\in\mathbb{C})$$

The following is an example: $2X+3Y$, which can be printed and confirmed numerically as follows. 

In [37]:
print(2*pauli_X()+3*pauli_Y()) 

  (0, 1)	(2-3j)
  (1, 0)	(2+3j)


Two matrices can be multiplied $A_1\cdot A_2$. For example, a prodcut of Pauli $X$ and $Y$ is 
$$X\cdot Y=\begin{pmatrix} i&0\\ 0&-i\end{pmatrix},$$ which can be confirmed numerically as follows. 

In [39]:
print(pauli_X().dot(pauli_Y()))

  (0, 0)	1j
  (1, 1)	-1j


## Hermitian conjugate (Adjoint)

The Hermitian conjugate of a matrix is frequently used for quantum computation. For a complex matrix $A$, the adoint $A^\dagger$ is defined by taking the transpose and conjugate of $A$. With puthon, it can be obtained by the following command "np.conj(A).T".  

By definition, the Pauli matrices are self-adjoint: $X^\dagger=X, Y^\dagger=Y, Z^\dagger=Z$. We can confirm this easily. 

In [41]:
print(np.conj(pauli_X()).T) 

  (1, 0)	1
  (0, 1)	1


In [57]:
print(np.conj(pauli_Y()).T) 

  (1, 0)	(-0+1j)
  (0, 1)	-1j


In [58]:
print(np.conj(pauli_Z()).T) 

  (0, 0)	1
  (1, 1)	-1


Let's compute adjoint of a general random complex operator $A$

In [59]:
real_part = np.random.rand(2, 2)
imaginary_part = np.random.rand(2, 2)
A = real_part + 1j * imaginary_part

print(A)

[[0.92968976+0.21710619j 0.80823469+0.47402802j]
 [0.30193549+0.71597108j 0.97874133+0.52682928j]]


In [60]:
np.conj(A).T

array([[0.92968976-0.21710619j, 0.30193549-0.71597108j],
       [0.80823469-0.47402802j, 0.97874133-0.52682928j]])

For unitary matrices $U$ , there is a special property: 
$$U^\dagger U=UU^\dagger=I.$$
Let's check this for genral random matrics. First generate a random unitary matrix as follows. 

In [61]:
from scipy.linalg import qr

def generate_random_unitary_matrix(n):
    # Create a random complex matrix
    random_matrix = np.random.rand(n, n) + 1j * np.random.rand(n, n)
    # Perform QR decomposition
    q, r = qr(random_matrix)
    # Ensure the matrix is unitary
    d = np.diag(r)
    ph = d / np.abs(d)
    unitary_matrix = q @ np.diag(ph)
    return unitary_matrix

# Generate a random 2x2 unitary matrix
unitary_matrix = generate_random_unitary_matrix(2)
print("Random 2x2 Unitary Matrix:")
print(unitary_matrix)

Random 2x2 Unitary Matrix:
[[ 0.56149086+0.63586669j  0.3571954 -0.39091305j]
 [ 0.45286826+0.27443014j -0.3595774 +0.76831148j]]


Now we can confirm $U^\dagger U=I$ as follows. 

In [46]:
U=unitary_matrix 
U_dag=np.conj(U).T

print(U_dag.dot(U))

[[1.+0.00000000e+00j 0.-1.66533454e-16j]
 [0.+1.66533454e-16j 1.+0.00000000e+00j]]


## Eigenvalues and Eigenvectors

For a given matrix $A$, a value $a$ and vector $v$ are called eigenvalue and eigenvector, when they satisfy 
$$Av=a v$$

Let's learn how to compute $a$ and $v$ numerically through the following example. 

In [108]:
# Define a complex matrix
complex_matrix = np.array([[1 + 2j, 2 - 1j], [3 + 4j, 4 + 3j]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(complex_matrix)

print("Complex Matrix:")
print(complex_matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Complex Matrix:
[[1.+2.j 2.-1.j]
 [3.+4.j 4.+3.j]]

Eigenvalues:
[-1.0810155+1.59243621j  6.0810155+3.40756379j]

Eigenvectors:
[[ 0.725601  +0.j          0.28993452-0.26150814j]
 [-0.54484903-0.42028886j  0.92062559+0.j        ]]


Let's check they really satisfy the condition. Pick up the first eivenvalue and eigenvectors 

In [109]:
a=eigenvalues[0]
print(a)

(-1.0810155028955246+1.592436210518461j)


In [114]:
v=eigenvectors[:,0]
print(v)

[ 0.725601  +0.j         -0.54484903-0.42028886j]


Apply the matrix $A$ to $v$

In [115]:
A=complex_matrix 
A.dot(v)

array([-0.78438593+1.1554733j ,  1.25827345-0.41329855j])

Apply $a$ to $v$ and confirm $Av=av$

In [116]:
a*v

array([-0.78438593+1.1554733j ,  1.25827345-0.41329855j])

In [49]:
v= np.array([1 + 1j, 3 - 2j])
print(v)

[1.+1.j 3.-2.j]


In [51]:
np.sqrt(np.dot(np.conj(v).T,v))


(3.872983346207417+0j)

In [59]:
def pauli_H():
    op=sp.csr_matrix([[2,1-1j],[1+1j,3]])
    return op

In [57]:
print(pauli_H()) 

  (0, 0)	(2+0j)
  (0, 1)	(1-1j)
  (1, 0)	(1+1j)
  (1, 1)	(3+0j)


In [61]:
# Define a complex matrix
complex_matrix = np.array([[2, 1-1j], [1+1j, 3]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(complex_matrix)

print("Complex Matrix:")
print(complex_matrix)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Complex Matrix:
[[2.+0.j 1.-1.j]
 [1.+1.j 3.+0.j]]

Eigenvalues:
[1.-2.52702567e-16j 4.-1.91386643e-16j]

Eigenvectors:
[[ 0.81649658+0.j          0.40824829-0.40824829j]
 [-0.40824829-0.40824829j  0.81649658+0.j        ]]


In [63]:
a=eigenvalues[0]
print(a)

(1-2.5270256719560606e-16j)


In [65]:
v=eigenvectors[:,0]
print(v)

[ 0.81649658+0.j         -0.40824829-0.40824829j]


In [67]:
A=complex_matrix 
A.dot(v)

array([ 0.81649658-2.77555756e-16j, -0.40824829-4.08248290e-01j])

In [69]:
a*v

array([ 0.81649658-2.06330782e-16j, -0.40824829-4.08248290e-01j])

In [71]:
v= np.array([1 + 1j, 3 - 2j])
print(v)

[1.+1.j 3.-2.j]


In [73]:
np.sqrt(np.dot(np.conj(v).T,v))

(3.872983346207417+0j)